### ISSUE TITLE
Feature : NCZ support

### ISSUE THREAD

**Issue by emargee** [emargee/nsfw#4]
NCZ is a bespoke way of compressing NCA files with ZSTD (https://github.com/nicoboss/nsz). Current tooling is written in Python so the task is adapting the logic to work in C# and checking the results are byte-identical.

NSZ is a NSP containing a NCZ.

The initial goal is to read the headers metadata and be able to de-compress rather than compress.

NCZ's can be compressed using two types.. SOLID or BLOCK compression. The initial plan is to only support SOLID.

# Tasks
- [x] POC - Read NCZ metadata from NCZ file 
- [x] POC - SOLID - Read NCZ file and decompress to NCA file - new hash must match original hash. 
- [x] POC - SOLID - Read NSZ  and convert to NSP without needing to save NCA to filesystem (stream decompression)
- [x] POC - BLOCK - Read NCZ and decompress to NCA file.
- [x] POC - BLOCK - Read NSZ and convert to NSP
- [x] Tidy up code into usable classes - look at threading
- [x] NSFW - Allow NSZ - Print metadata about NCZ as part of validation output
- [x] NSFW - Update `Convert` action to decompress NSZ files into Standard NSP

## Stretch goals
- [ ] Compress NCA using SOLID
- [ ] Compress NCA using BLOCK

### References
ZSTD Library : https://github.com/oleg-st/ZstdSharp
